## Holiday Package Prediciton

### 1) Problemm statement.
"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base.
One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information.
The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.
However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.
### 2) Data Collection.
The Dataset is collected from https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction
The data consists of 20 column and 4888 rows.

In [1]:
## importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

C:\Users\Rv\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df=pd.read_csv("D:/Travel_random.csv")
df.head(5)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [3]:
df.shape

(4888, 20)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [5]:
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

## Data Cleaning
### Handling Missing values
1. Handling Missing values
2. Handling Duplicates
3. Check data type
4. Understand the dataset

In [7]:
## chekc all the categorical feature
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [8]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [9]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [10]:
df["Gender"]=df["Gender"].replace("Fe Male","Female")
df["MaritalStatus"]=df["MaritalStatus"].replace("Single","Unmarried")

In [11]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [12]:
df["Gender"].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [13]:
df.head(5)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [14]:
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [15]:
## Check Misssing Values
##these are the features with nan value
feature_with_na=[feature for feature in df.columns if df[feature].isnull().sum()]
for i in feature_with_na:
    print(i,np.round(df[i].isnull().sum()))
    
print("the total feature are having null:",len(feature_with_na))

Age 226
TypeofContact 25
DurationOfPitch 251
NumberOfFollowups 45
PreferredPropertyStar 26
NumberOfTrips 140
NumberOfChildrenVisiting 66
MonthlyIncome 233
the total feature are having null: 8

In [16]:
df[feature_with_na].select_dtypes(exclude="object").describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [17]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [18]:
df[feature_with_na]

,Age,TypeofContact,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
0,41.0,Self Enquiry,6.0,3.0,3.0,1.0,0.0,20993.0
1,49.0,Company Invited,14.0,4.0,4.0,2.0,2.0,20130.0
2,37.0,Self Enquiry,8.0,4.0,3.0,7.0,0.0,17090.0
3,33.0,Company Invited,9.0,3.0,3.0,2.0,1.0,17909.0
4,NaN,Self Enquiry,8.0,3.0,4.0,1.0,0.0,18468.0
...,...,...,...,...,...,...,...,...
4883,49.0,Self Enquiry,9.0,5.0,4.0,2.0,1.0,26576.0
4884,28.0,Company Invited,31.0,5.0,3.0,3.0,2.0,21212.0
4885,52.0,Self Enquiry,17.0,4.0,4.0,7.0,3.0,31820.0
4886,19.0,Self Enquiry,16.0,4.0,3.0,3.0,2.0,20289.0
4887,36.0,Self Enquiry,14.0,4.0,4.0,3.0,2.0,24041.0

In [19]:
len(df["NumberOfChildrenVisiting"].unique()),len(df["TypeofContact"].unique()),len(df["NumberOfFollowups"].unique())

(5, 3, 7)

## Imputing Null values
1. Impute Median value for Age column
2. Impute Mode for Type of Contract
3. Impute Median for Duration of Pitch
4. Impute Mode for NumberofFollowup as it is Discrete feature
5. Impute Mode for PreferredPropertyStar
6. Impute Median for NumberofTrips
7. Impute Mode for NumberOfChildrenVisiting
8. Impute Median for MonthlyIncome

In [20]:
#age
df.Age.fillna(df.Age.median(),inplace=True)

#type of contract
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)

#DurationOfPitch
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)

#NumberOfFollowups
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)

#PreferredPropertyStar
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)

#number of trips
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace=True)


#NumberOfChildrenVisiting
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)

#MonthlyIncome
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [21]:
df.isna().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [22]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [23]:
df.drop("CustomerID",inplace=True,axis=1)

In [24]:
df.head(5)

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

## Feature Engineering

### Feature Extraction

In [25]:
# create new column for feature,due to no of person visiting and no of chilern visiting are these feature relate in same family members
df["totalvisiting"]=df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]
df.drop(columns=["NumberOfPersonVisiting","NumberOfChildrenVisiting"],axis=1,inplace=True)

In [26]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,totalvisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [27]:
len(df.columns)

18

In [28]:
## get all the numeric features
num_feature=[feature for feature in df.columns if df[feature].dtype !="O"]
print("the number of numerical feature in our data:",len(num_feature))

the number of numerical feature in our data: 12

In [29]:
## get all the categorical feature
cat_feature=[feature  for feature in df.columns if df[feature].dtype=="O"]
print("the number of categorical feature in our dataset:",len(cat_feature))

the number of categorical feature in our dataset: 6

In [30]:
## Discrete features 
discrete_feature=[feature for feature in num_feature if len(df[feature].unique())<=25]
print("the number of discrete feature in dataset:",len(discrete_feature))

the number of discrete feature in dataset: 9

In [31]:
##continous fature
con_feature=[feature for feature in num_feature if feature not in discrete_feature]
print("the number of continous feature in dataset:",len(con_feature))

the number of continous feature in dataset: 3

## Train Test Split And Model Training

In [32]:
from sklearn.model_selection import train_test_split
x = df.drop(['ProdTaken'], axis=1)
y = df['ProdTaken']

In [33]:
x.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,totalvisiting
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [34]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [35]:
# separate dataset into train and test
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)
xtrain.shape,ytest.shape

((3910, 17), (978,))

In [36]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4888 non-null   float64
 1   TypeofContact           4888 non-null   object
 2   CityTier                4888 non-null   int64
 3   DurationOfPitch         4888 non-null   float64
 4   Occupation              4888 non-null   object
 5   Gender                  4888 non-null   object
 6   NumberOfFollowups       4888 non-null   float64
 7   ProductPitched          4888 non-null   object
 8   PreferredPropertyStar   4888 non-null   float64
 9   MaritalStatus           4888 non-null   object
 10  NumberOfTrips           4888 non-null   float64
 11  Passport                4888 non-null   int64
 12  PitchSatisfactionScore  4888 non-null   int64
 13  OwnCar                  4888 non-null   int64
 14  Designation             4888 non-null   object
 15  MonthlyIncome           4888 non-null   float64
 16  totalvisiting           4888 non-null   float64
dtypes: float64(7), int64(4), object(6)
memory usage: 649.3+ KB

In [37]:
# Create Column Transformer with 3 types of transformers
cat_feature=x.select_dtypes(include="object").columns
num_feature=x.select_dtypes(exclude="object").columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

cat_transform=OneHotEncoder(drop="first")
num_transform=StandardScaler()

preprocessor=ColumnTransformer(
[
    ("OneHotEncoder",cat_transform,cat_feature),
    ("StandardScaler",num_transform,num_feature)
])

In [38]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'totalvisiting'],
      dtype='object'))])

In [39]:
xtrain=preprocessor.fit_transform(xtrain)

In [40]:
pd.DataFrame(xtrain)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,0.679690,0.782966,-0.382245,-0.774151
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.721400,0.690023,0.282777,-0.725271,1.511598,-0.632399,0.679690,0.782966,-0.459799,0.643615
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,0.282777,1.771041,0.418708,-0.632399,0.679690,0.782966,-0.245196,-0.065268
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,1.408395,-1.277194,0.213475,-0.065268
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,2.400396,-1.720227,-0.725271,1.511598,-0.632399,-0.049015,-1.277194,-0.024889,2.061382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.653841,1.284279,-0.725271,-0.674182,-0.632399,-1.506426,0.782966,-0.536973,0.643615
3906,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.455047,-0.898180,-0.718725,1.771041,-1.220627,-0.632399,1.408395,0.782966,1.529609,-0.065268
3907,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.455047,1.545210,0.282777,-0.725271,2.058043,-0.632399,-0.777720,0.782966,-0.360576,0.643615
3908,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.455047,1.789549,1.284279,-0.725271,-0.127737,-0.632399,-1.506426,0.782966,-0.252799,0.643615
3909,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.776011,0.282777,-0.725271,-1.220627,1.581280,-0.049015,-1.277194,-1.082511,-1.483035

In [41]:
xtest=preprocessor.transform(xtest)

In [42]:
pd.DataFrame(xtest)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.455047,-0.287333,1.284279,-0.725271,-1.220627,-0.632399,-0.777720,-1.277194,-0.737510,-0.774151
1,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.366823,-0.531672,0.282777,0.522885,-1.220627,1.581280,1.408395,-1.277194,-0.670411,-0.065268
2,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.455047,0.812193,0.282777,-0.725271,0.965153,-0.632399,1.408395,0.782966,-0.420832,-0.774151
3,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,-0.721400,2.522566,2.285781,-0.725271,1.511598,-0.632399,-0.049015,0.782966,-0.113658,0.643615
4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.455047,-1.020350,0.282777,0.522885,-0.127737,1.581280,0.679690,0.782966,-0.317047,2.061382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,-0.721400,-1.020350,0.282777,-0.725271,1.511598,-0.632399,1.408395,0.782966,0.498219,0.643615
974,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.721400,-1.142519,0.282777,1.771041,-0.674182,1.581280,-1.506426,-1.277194,-1.184015,-1.483035
975,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.721400,1.056532,1.284279,-0.725271,-0.674182,1.581280,1.408395,0.782966,0.690012,0.643615
976,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.287333,-2.721728,-0.725271,-0.674182,-0.632399,1.408395,0.782966,-0.228278,-0.774151
977,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.776011,0.282777,-0.725271,-0.674182,-0.632399,1.408395,0.782966,-0.446113,2.061382

## Random Forest Classifier Training

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score,roc_curve
log=LogisticRegression()
log.fit(xtrain,ytrain)
ypred=log.predict(xtest)



print("training data:",log.score(xtrain,ytrain))
print("testing data:",log.score(xtest,ytest))
print("-------------------------------------------------------------")
print(metrics.classification_report(ytest,ypred))
print("-----------------------------------------------------------------")
print("accuracy score: ",round(accuracy_score(ytest,ypred)*100,2),"%")

training data: 0.8457800511508952
testing data: 0.8353783231083844
-------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.85      0.97      0.90       787
           1       0.68      0.29      0.41       191

    accuracy                           0.84       978
   macro avg       0.77      0.63      0.66       978
weighted avg       0.82      0.84      0.81       978

-----------------------------------------------------------------
accuracy score:  83.54 %

In [44]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score,roc_curve,f1_score

In [67]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
     -------------------------------------- 101.7/101.7 MB 4.2 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\rv\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\rv\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\rv\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\rv\anaconda3\lib\site-packages)

In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report,ConfusionMatrixDisplay, \
                            precision_score, recall_score, f1_score, roc_auc_score,roc_curve 

from sklearn.model_selection import (GridSearchCV,
                                     StratifiedKFold,
                                     cross_val_score)
from sklearn import feature_selection
from sklearn import model_selection
from sklearn import metrics
from sklearn.model_selection import KFold

In [70]:
models={
    "logistcregression":LogisticRegression(),
    "knn":KNeighborsClassifier(),
    "Gaussian":GaussianNB(),
    "Decision Tree":DecisionTreeClassifier(),
    "svc":SVC(),
    "Random Forest":RandomForestClassifier(),
    "Gradient Boost":GradientBoostingClassifier(),
    "adaboost":AdaBoostClassifier(),
    "xgboost":XGBClassifier()
    
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(xtrain,ytrain)
    
    #make prediction
    ytrain_pred=model.predict(xtrain)
    ytest_pred=model.predict(xtest)
    
    
    #performace of training data
    model_train_acc=accuracy_score(ytrain,ytrain_pred)
    model_train_f1=f1_score(ytrain,ytrain_pred)
    model_train_precision=precision_score(ytrain,ytrain_pred)
    model_train_recall=recall_score(ytrain,ytrain_pred)
    model_train_roc_score=roc_auc_score(ytrain,ytrain_pred)
    class_report_train=classification_report(ytrain,ytrain_pred)
    
    
    #performance of test data
    model_test_acc=accuracy_score(ytest,ytest_pred)
    model_test_f1=f1_score(ytest,ytest_pred)
    model_test_precision=precision_score(ytest,ytest_pred)
    model_test_recall=recall_score(ytest,ytest_pred)
    model_test_roc_score=roc_auc_score(ytest,ytest_pred)
    class_report_test=classification_report(ytest,ytest_pred)
    
    print(list(models.keys())[i])
    print('\n')
    print("model perfromace of tha training data")
    print("-accuracy score:",model_train_acc)
    print("-f1 score:",model_train_f1)
    print("-precision score:",model_train_precision)
    print("-recall score:",model_train_recall)
    print("-roc_auc_score:",model_train_roc_score)
    print("report:",class_report_train)
    
    print("----------------------------------------")
    print("model perfromace of tha testing data")
    print("-accuracy score:",model_test_acc)
    print("-f1 score:",model_test_f1)
    print("-precision score:",model_test_precision)
    print("-recall score:",model_test_recall)
    print("-roc_auc_score:",model_test_roc_score)
    print("report:",class_report_test)
    
    
    print("=========================================")
    print("\n")

logistcregression


model perfromace of tha training data
-accuracy score: 0.8457800511508952
-f1 score: 0.42296650717703344
-precision score: 0.6993670886075949
-recall score: 0.30315500685871055
-roc_auc_score: 0.6366450922379061
report:               precision    recall  f1-score   support

           0       0.86      0.97      0.91      3181
           1       0.70      0.30      0.42       729

    accuracy                           0.85      3910
   macro avg       0.78      0.64      0.67      3910
weighted avg       0.83      0.85      0.82      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8353783231083844
-f1 score: 0.41025641025641024
-precision score: 0.6829268292682927
-recall score: 0.2931937172774869
-roc_auc_score: 0.6300784342423011
report:               precision    recall  f1-score   support

           0       0.85      0.97      0.90       787
           1       0.68      0.29      0.41       191

    accuracy                           0.84       978
   macro avg       0.77      0.63      0.66       978
weighted avg       0.82      0.84      0.81       978

=========================================


knn


model perfromace of tha training data
-accuracy score: 0.9470588235294117
-f1 score: 0.8428246013667426
-precision score: 0.9438775510204082
-recall score: 0.7613168724279835
-roc_auc_score: 0.8754713881159094
report:               precision    recall  f1-score   support

           0       0.95      0.99      0.97      3181
           1       0.94      0.76      0.84       729

    accuracy                           0.95      3910
   macro avg       0.95      0.88      0.91      3910
weighted avg       0.95      0.95      0.94      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8875255623721882
-f1 score: 0.6540880503144655
-precision score: 0.8188976377952756
-recall score: 0.5445026178010471
-roc_auc_score: 0.7576388565498248
report:               precision    recall  f1-score   support

           0       0.90      0.97      0.93       787
           1       0.82      0.54      0.65       191

    accuracy                           0.89       978
   macro avg       0.86      0.76      0.79       978
weighted avg       0.88      0.89      0.88       978

=========================================


Gaussian


model perfromace of tha training data
-accuracy score: 0.7066496163682865
-f1 score: 0.46175504458000943
-precision score: 0.3509272467902996
-recall score: 0.6748971193415638
-roc_auc_score: 0.6944117787842683
report:               precision    recall  f1-score   support

           0       0.91      0.71      0.80      3181
           1       0.35      0.67      0.46       729

    accuracy                           0.71      3910
   macro avg       0.63      0.69      0.63      3910
weighted avg       0.80      0.71      0.74      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.6942740286298569
-f1 score: 0.46126126126126127
-precision score: 0.3516483516483517
-recall score: 0.6701570680628273
-roc_auc_score: 0.6851420664329384
report:               precision    recall  f1-score   support

           0       0.90      0.70      0.79       787
           1       0.35      0.67      0.46       191

    accuracy                           0.69       978
   macro avg       0.62      0.69      0.62       978
weighted avg       0.79      0.69      0.72       978

=========================================


Decision Tree


model perfromace of tha training data
-accuracy score: 1.0
-f1 score: 1.0
-precision score: 1.0
-recall score: 1.0
-roc_auc_score: 1.0
report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3181
           1       1.00      1.00      1.00       729

    accuracy                           1.00      3910
   macro avg       1.00      1.00      1.00      3910
weighted avg       1.00      1.00      1.00      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.9141104294478528
-f1 score: 0.7754010695187167
-precision score: 0.7923497267759563
-recall score: 0.7591623036649214
-roc_auc_score: 0.8554388392530452
report:               precision    recall  f1-score   support

           0       0.94      0.95      0.95       787
           1       0.79      0.76      0.78       191

    accuracy                           0.91       978
   macro avg       0.87      0.86      0.86       978
weighted avg       0.91      0.91      0.91       978

=========================================


svc


model perfromace of tha training data
-accuracy score: 0.9012787723785166
-f1 score: 0.6614035087719299
-precision score: 0.9172749391727494
-recall score: 0.5171467764060357
-roc_auc_score: 0.7532291568292361
report:               precision    recall  f1-score   support

           0       0.90      0.99      0.94      3181
           1       0.92      0.52      0.66       729

    accuracy                           0.90      3910
   macro avg       0.91      0.75      0.80      3910
weighted avg       0.90      0.90      0.89      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8650306748466258
-f1 score: 0.5217391304347826
-precision score: 0.8470588235294118
-recall score: 0.3769633507853403
-roc_auc_score: 0.680222463194449
report:               precision    recall  f1-score   support

           0       0.87      0.98      0.92       787
           1       0.85      0.38      0.52       191

    accuracy                           0.87       978
   macro avg       0.86      0.68      0.72       978
weighted avg       0.86      0.87      0.84       978

=========================================


Random Forest


model perfromace of tha training data
-accuracy score: 1.0
-f1 score: 1.0
-precision score: 1.0
-recall score: 1.0
-roc_auc_score: 1.0
report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3181
           1       1.00      1.00      1.00       729

    accuracy                           1.00      3910
   macro avg       1.00      1.00      1.00      3910
weighted avg       1.00      1.00      1.00      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.9253578732106339
-f1 score: 0.7725856697819313
-precision score: 0.9538461538461539
-recall score: 0.6492146596858639
-roc_auc_score: 0.8207953857514453
report:               precision    recall  f1-score   support

           0       0.92      0.99      0.96       787
           1       0.95      0.65      0.77       191

    accuracy                           0.93       978
   macro avg       0.94      0.82      0.86       978
weighted avg       0.93      0.93      0.92       978

=========================================


Gradient Boost


model perfromace of tha training data
-accuracy score: 0.8938618925831202
-f1 score: 0.6381865736704446
-precision score: 0.8755980861244019
-recall score: 0.5020576131687243
-roc_auc_score: 0.7428552762479901
report:               precision    recall  f1-score   support

           0       0.90      0.98      0.94      3181
           1       0.88      0.50      0.64       729

    accuracy                           0.89      3910
   macro avg       0.89      0.74      0.79      3910
weighted avg       0.89      0.89      0.88      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8588957055214724
-f1 score: 0.5208333333333334
-precision score: 0.7731958762886598
-recall score: 0.39267015706806285
-roc_auc_score: 0.6823579501985804
report:               precision    recall  f1-score   support

           0       0.87      0.97      0.92       787
           1       0.77      0.39      0.52       191

    accuracy                           0.86       978
   macro avg       0.82      0.68      0.72       978
weighted avg       0.85      0.86      0.84       978

=========================================


adaboost


model perfromace of tha training data
-accuracy score: 0.8565217391304348
-f1 score: 0.48673376029277216
-precision score: 0.7307692307692307
-recall score: 0.36488340192043894
-roc_auc_score: 0.6670377399416719
report:               precision    recall  f1-score   support

           0       0.87      0.97      0.92      3181
           1       0.73      0.36      0.49       729

    accuracy                           0.86      3910
   macro avg       0.80      0.67      0.70      3910
weighted avg       0.84      0.86      0.84      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8353783231083844
-f1 score: 0.43109540636042404
-precision score: 0.6630434782608695
-recall score: 0.3193717277486911
-roc_auc_score: 0.6399908194016645
report:               precision    recall  f1-score   support

           0       0.85      0.96      0.90       787
           1       0.66      0.32      0.43       191

    accuracy                           0.84       978
   macro avg       0.76      0.64      0.67       978
weighted avg       0.82      0.84      0.81       978

=========================================

xgboost


model perfromace of tha training data
-accuracy score: 0.99923273657289
-f1 score: 0.9979381443298969
-precision score: 1.0
-recall score: 0.9958847736625515
-roc_auc_score: 0.9979423868312758
report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3181
           1       1.00      1.00      1.00       729

    accuracy                           1.00      3910
   macro avg       1.00      1.00      1.00      3910
weighted avg       1.00      1.00      1.00      3910

----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.9355828220858896
-f1 score: 0.8108108108108107
-precision score: 0.9507042253521126
-recall score: 0.7068062827225131
-roc_auc_score: 0.8489558732545222
report:               precision    recall  f1-score   support

           0       0.93      0.99      0.96       787
           1       0.95      0.71      0.81       191

    accuracy                           0.94       978
   macro avg       0.94      0.85      0.89       978
weighted avg       0.94      0.94      0.93       978

=========================================

## Hyperparameter Training

In [47]:
## Hyperparameter Training
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

In [48]:
rf_params

{'max_depth': [5, 8, 15, None, 10],
 'max_features': [5, 7, 'auto', 8],
 'min_samples_split': [2, 8, 15, 20],
 'n_estimators': [100, 200, 500, 1000]}

In [49]:
# Models list for Hyperparameter tuning
randomcv_models = [
                   ("RF", RandomForestClassifier(), rf_params)
                   
                   ]

In [50]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]})]

In [51]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(xtrain, ytrain)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for RF -------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 7, 'max_depth': 15}

In [83]:
## Hyperparameter Training
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}
gradient_params={"loss": ['log_loss','deviance','exponential'],
             "criterion": ['friedman_mse','squared_error','mse'],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500],
              "max_depth": [5, 8, 15, None, 10]
                }
adaboost_params={'n_estimators' : [50, 70, 90, 120, 180, 200],
    'learning_rate' : [0.001, 0.01, 0.1, 1, 10]}

xgboost_params={'max_depth':[3, 18,1],
        'gamma': [1,9],
        'reg_alpha' :[40,180,1],
        'reg_lambda' : [0,1],
        'colsample_bytree' : [0.5, 0.8, 1, 0.3, 0.4],
        'min_child_weight' : [0, 10, 1],
        'n_estimators': [100,200,300]

    }

In [84]:
xgboost_params

{'max_depth': [3, 18, 1],
 'gamma': [1, 9],
 'reg_alpha': [40, 180, 1],
 'reg_lambda': [0, 1],
 'colsample_bytree': [0.5, 0.8, 1, 0.3, 0.4],
 'min_child_weight': [0, 10, 1],
 'n_estimators': [100, 200, 300]}

In [79]:
rf_params

{'max_depth': [5, 8, 15, None, 10],
 'max_features': [5, 7, 'auto', 8],
 'min_samples_split': [2, 8, 15, 20],
 'n_estimators': [100, 200, 500, 1000]}

In [80]:
gradient_params

{'loss': ['log_loss', 'deviance', 'exponential'],
 'criterion': ['friedman_mse', 'squared_error', 'mse'],
 'min_samples_split': [2, 8, 15, 20],
 'n_estimators': [100, 200, 500],
 'max_depth': [5, 8, 15, None, 10]}

In [81]:
adaboost_params

{'n_estimators': [50, 70, 90, 120, 180, 200],
 'learning_rate': [0.001, 0.01, 0.1, 1, 10]}

In [56]:
rfc=RandomForestClassifier(random_state=42)
rcv=RandomizedSearchCV(estimator=rfc,param_distributions=rf_params,n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
rcv.fit(xtrain,ytrain)
print("best params:",rcv.best_params_)
print("best score:",rcv.best_score_)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
best params: {'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}
best score: 0.9168808962171613

In [63]:
gb=GradientBoostingClassifier(random_state=42)
gbcv=RandomizedSearchCV(estimator=gb,param_distributions=gradient_params,n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
gbcv.fit(xtrain,ytrain)
print("best params:",gbcv.best_params_)
print("best score:",gbcv.best_score_)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
best params: {'n_estimators': 500, 'min_samples_split': 8, 'max_depth': 15, 'loss': 'log_loss', 'criterion': 'squared_error'}
best score: 0.9306906588068747

In [65]:
ab=AdaBoostClassifier(random_state=42)
abcv=RandomizedSearchCV(estimator=ab,param_distributions=adaboost_params,n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
abcv.fit(xtrain,ytrain)
print("best params:",abcv.best_params_)
print("best score:",abcv.best_score_)

Fitting 3 folds for each of 30 candidates, totalling 90 fits
best params: {'n_estimators': 50, 'learning_rate': 1}
best score: 0.8452701568034754

In [85]:
xg=XGBClassifier()
xgrv=RandomizedSearchCV(estimator=xg,param_distributions=xgboost_params,cv=3,verbose=2,n_jobs=-1)
xgrv.fit(xtrain,ytrain)
print("best_params:",xgrv.best_params_)
print("best_score:",xgrv.best_score_)

Fitting 3 folds for each of 10 candidates, totalling 30 fits
best_params: {'reg_lambda': 1, 'reg_alpha': 1, 'n_estimators': 300, 'min_child_weight': 0, 'max_depth': 3, 'gamma': 1, 'colsample_bytree': 1}
best_score: 0.8677752457362041

In [86]:
models={"Random Forest":RandomForestClassifier(n_estimators=500,min_samples_split=2,
                                          max_features=8,max_depth=None),
        "gradient boositng":GradientBoostingClassifier(n_estimators=500, min_samples_split=8, max_depth=15, loss='log_loss', criterion='squared_error'),
        "adaboost":AdaBoostClassifier(n_estimators=50, learning_rate=1),
        "xgboost":XGBClassifier(reg_lambda=1, reg_alpha=1, n_estimators=300, min_child_weight=0, max_depth= 3, gamma=1, colsample_bytree= 1)
    
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(xtrain,ytrain)
    
    #make prediction
    ytrain_pred=model.predict(xtrain)
    ytest_pred=model.predict(xtest)
    
    
    #performace of training data
    model_train_acc=accuracy_score(ytrain,ytrain_pred)
    model_train_f1=f1_score(ytrain,ytrain_pred)
    model_train_precision=precision_score(ytrain,ytrain_pred)
    model_train_recall=recall_score(ytrain,ytrain_pred)
    model_train_roc_score=roc_auc_score(ytrain,ytrain_pred)
    
    #performance of test data
    model_test_acc=accuracy_score(ytest,ytest_pred)
    model_test_f1=f1_score(ytest,ytest_pred)
    model_test_precision=precision_score(ytest,ytest_pred)
    model_test_recall=recall_score(ytest,ytest_pred)
    model_test_roc_score=roc_auc_score(ytest,ytest_pred)
    
    print(list(models.keys())[i])
    print('\n')
    print("model perfromace of tha training data")
    print("-accuracy score:",model_train_acc)
    print("-f1 score:",model_train_f1)
    print("-precision score:",model_train_precision)
    print("-recall score:",model_train_recall)
    print("-roc_auc_score:",model_train_roc_score)
    
    print("----------------------------------------")
    print("model perfromace of tha testing data")
    print("-accuracy score:",model_test_acc)
    print("-f1 score:",model_test_f1)
    print("-precision score:",model_test_precision)
    print("-recall score:",model_test_recall)
    print("-roc_auc_score:",model_test_roc_score)
    
    
    print("=========================================")
    print("\n")
    
    print(classification_report(ytest,ytest_pred))

Random Forest


model perfromace of tha training data
-accuracy score: 1.0
-f1 score: 1.0
-precision score: 1.0
-recall score: 1.0
-roc_auc_score: 1.0
----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.9325153374233128
-f1 score: 0.7975460122699387
-precision score: 0.9629629629629629
-recall score: 0.680628272251309
-roc_auc_score: 0.8371375160494157
=========================================


              precision    recall  f1-score   support

           0       0.93      0.99      0.96       787
           1       0.96      0.68      0.80       191

    accuracy                           0.93       978
   macro avg       0.95      0.84      0.88       978
weighted avg       0.93      0.93      0.93       978

gradient boositng


model perfromace of tha training data
-accuracy score: 1.0
-f1 score: 1.0
-precision score: 1.0
-recall score: 1.0
-roc_auc_score: 1.0
----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.9611451942740287
-f1 score: 0.8914285714285715
-precision score: 0.9811320754716981
-recall score: 0.8167539267015707
-roc_auc_score: 0.906470991305042
=========================================


              precision    recall  f1-score   support

           0       0.96      1.00      0.98       787
           1       0.98      0.82      0.89       191

    accuracy                           0.96       978
   macro avg       0.97      0.91      0.93       978
weighted avg       0.96      0.96      0.96       978

adaboost


model perfromace of tha training data
-accuracy score: 0.8565217391304348
-f1 score: 0.48673376029277216
-precision score: 0.7307692307692307
-recall score: 0.36488340192043894
-roc_auc_score: 0.6670377399416719
----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8353783231083844
-f1 score: 0.43109540636042404
-precision score: 0.6630434782608695
-recall score: 0.3193717277486911
-roc_auc_score: 0.6399908194016645
=========================================


              precision    recall  f1-score   support

           0       0.85      0.96      0.90       787
           1       0.66      0.32      0.43       191

    accuracy                           0.84       978
   macro avg       0.76      0.64      0.67       978
weighted avg       0.82      0.84      0.81       978

xgboost


model perfromace of tha training data
-accuracy score: 0.8884910485933504
-f1 score: 0.6202090592334494
-precision score: 0.8496420047732697
-recall score: 0.4883401920438957
-roc_auc_score: 0.7342675496528814
----------------------------------------
model perfromace of tha testing data
-accuracy score: 0.8670756646216768
-f1 score: 0.563758389261745
-precision score: 0.7850467289719626
-recall score: 0.4397905759162304
-roc_auc_score: 0.7052828356074163
=========================================


              precision    recall  f1-score   support

           0       0.88      0.97      0.92       787
           1       0.79      0.44      0.56       191

    accuracy                           0.87       978
   macro avg       0.83      0.71      0.74       978
weighted avg       0.86      0.87      0.85       978